### PR TITLE
fix formatting of carrige return

### LINKED ISSUE #173: ast/formatter: carriege returns dropped by nashfmt

### PR DESCRIPTION
**Pull request by tiago4orion**
Closes #173

### CODE REVIEW

File: ast/node_fmt_test.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+import (
+	"testing"
+
+	"github.com/NeowayLabs/nash/token"
+)
+
+func testPrinter(t *testing.T, node Node, expected string) {
+	if node.String() != expected {
+		t.Errorf("Values differ: '%s' != '%s'", node.String(), expected)
```
Comment (katcipis) [inline ast/node_fmt_test.go]: You can just pass node, no ? (no need to call .String())

Comment (tiago4orion) [inline ast/node_fmt_test.go]: =)
